### ISSUE TITLE
_bluebird2.default.mapSeries is not a function

### ISSUE THREAD

**Issue by Christilut** [matrix-org/matrix-js-sdk#531]
Getting this error since I upgraded from 0.7.13 to 0.8.2

```
Caught /sync error TypeError: _bluebird2.default.mapSeries is not a function
    at SyncApi._callee3$ (eval at <anonymous> (http://localhost:8080/app.js:3664:1), <anonymous>:845:74)
    at tryCatch (eval at <anonymous> (http://localhost:8080/app.js:3716:1), <anonymous>:65:40)
    at Generator.invoke [as _invoke] (eval at <anonymous> (http://localhost:8080/app.js:3716:1), <anonymous>:303:22)
    at Generator.prototype.(anonymous function) [as next] (eval at <anonymous> (http://localhost:8080/app.js:3716:1), <anonymous>:117:21)
    at Generator.tryCatcher (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:4594:23)
    at PromiseSpawn._next (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:1721:49)
    at SyncApi.eval (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:1738:15)
    at SyncApi.eval [as _processSyncResponse] (eval at <anonymous> (http://localhost:8080/app.js:3664:1), <anonymous>:1091:21)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:3664:1), <anonymous>:609:14)
    at tryCatcher (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:4594:23)
    at Promise._settlePromiseFromHandler (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:2698:31)
    at Promise._settlePromiseAt (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:2772:18)
    at Async._drainQueue (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:180:12)
    at Async._drainQueues (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:185:10)
    at Async.drainQueues (eval at <anonymous> (http://localhost:8080/app.js:773:1), <anonymous>:67:14)
```
Doesn't load any chats after this error.

Using Chrome 60

This is with a webpack build (2.3.3)

**Comment by jaller94** [comment]
Do you have some source snippet to reproduce this?

I'm building an app right now and have not run across this yet.

**Comment by Christilut** [comment]
I downgraded the sdk but I'll try again in a few days. Maybe it is already fixed in the latest version.

**Comment by Christilut** [comment]
Sorry this took so long. Just upgraded my app to the latest SDK version and it appears to be fixed.
